<?php

$_COS_LANG_MODULE = array();
$_COS_LANG_MODULE['Newsletter'] = 'Nyhedsbrev';
$_COS_LANG_MODULE['email_exists'] = 'Email eksisterer';
$_COS_LANG_MODULE['subscribe_to_newsletter'] = 'Tilmeld';
$_COS_LANG_MODULE['subscribe'] = 'Tilmeld dig';
$_COS_LANG_MODULE['verify_subscribed'] = 'Du er nu tilmeldt nyhedsbrevet';
$_COS_LANG_MODULE['email_already_subscribed'] = 'Din mail er allerede tilmeldt nyhedsbrevet';
$_COS_LANG_MODULE['unsubscribe'] = 'Afmeld';
$_COS_LANG_MODULE['error_email'] = 'Indtast en korrekt email adresse';
$_COS_LANG_MODULE['subscribed_message'] = 'Der er afsendt en bekræftelses email. Når du har svaret på denne er du tilmeldt nyhedsbrevet';
$_COS_LANG_MODULE['unsubscribed_message'] = 'Der er afsendt en bekræftelses email. Når du har svaret på denne er du afmeldt nyhedsbrevet';
$_COS_LANG_MODULE['subscribe_subject'] = 'Tilmeldning Nyhedsbrev';
$_COS_LANG_MODULE['send_newsletter'] = 'Send nyhedsbrev';
$_COS_LANG_MODULE['title'] = 'Overskrift';
$_COS_LANG_MODULE['unsubscribe_to_newsletter'] = 'Afmeld nyhedsbrev';
$_COS_LANG_MODULE['send'] = 'Afsend';
$_COS_LANG_MODULE['unsubscribe_subject'] = 'Afmeld dig nyhedsbrev';
$_COS_LANG_MODULE['verify_unsubscribed'] = 'Du er nu afmeldt nyhedsbrevet';
$_COS_LANG_MODULE['email_already_unsubscribed'] = 'Din email er allerede afmeldt';
$_COS_LANG_MODULE['email_not_exists'] = 'Denne email eksister ikke i vores database';
$_COS_LANG_MODULE['newsletter_verify_title'] = 'Verificer tilmeldelse til nyhedsbrev';
$_COS_LANG_MODULE['newsletter_verify_unsubscribe_title'] = 'Verificering af afmeldelse af nyhedsbrev';

$_COS_LANG_MODULE['No title'] = 'Ingen titel';
$_COS_LANG_MODULE['No content'] = 'Ingen indhold';

$_COS_LANG_MODULE['newsletter_has_been_sent'] = 'Nyhedsbrev er afsendt!';
$_COS_LANG_MODULE['test_email'] = 'Test Email. Skriv en email her, hvis det er en test. Nyhedsbrevet vil i så fald kun blive sendt til den angive email adresse';

$_COS_LANG_MODULE['newsletter_test_has_been_sent'] = "Test Nyhedsbrev er afsendt. Ryd feltet 'Test Email' Hvis du vil sende nyhedsbrevet til hele listen!";
$_COS_LANG_MODULE['error_test_email'] = 'Din test email er ikke korrekt!';

$_COS_LANG_MODULE['admin_newsletter_note'] = "Når du sender email skal du være klar over, at det kan tage et par minutter - især hvis du har flere hundrede medlemmer på din liste. Undgå derfor at trykke mere end en gang på Send, men vent i stedet blot på bekræftelse mens du drikker en kop kaffe!";
$_COS_LANG_MODULE['report_email_error'] = 'Fejl i denne email. Du bør slette den!';
$_COS_LANG_MODULE['report_email_correct'] = 'Denne email er ok';

$_COS_LANG_MODULE['validate_all_emails'] = 'Validere emails';
$_COS_LANG_MODULE['validate_all_message'] = 'Det kan tage lidt tid at validere alle emails da det bliver gjort grundigt. Ligeledes er det afhængigt af antallet af emails. Tryk derfor kun en gang og drik en kop kaffe mens du venter!';
$_COS_LANG_MODULE['validate_all'] = 'Valider alle emails!';

$_COS_LANG_MODULE['delete_broken_emails'] = 'Slet ovenstående emails';
$_COS_LANG_MODULE['broken_emails_deleted'] = 'Fejlagtige emails er blevet slettet';

