<?php

// Translation of file /home/dennis/www/coscms/modules/newsletter/views/form_send.php

$_COS_LANG_MODULE['newsletter_send_newsletter'] = 'Send newsletter';
$_COS_LANG_MODULE['newsletter_title'] = 'Title';
$_COS_LANG_MODULE['newsletter_content'] = 'Content';
$_COS_LANG_MODULE['newsletter_test_email'] = 'Test Email';
$_COS_LANG_MODULE['newsletter_send'] = 'Send';

// Translation of file /home/dennis/www/coscms/modules/newsletter/verify.php

$_COS_LANG_MODULE['newsletter_verify_title'] = 'Verify Subscription';

// Translation of file /home/dennis/www/coscms/modules/newsletter/verify_unsubscribe.php

$_COS_LANG_MODULE['newsletter_verify_unsubscribe_title'] = 'Unsubscribe';

// Translation of file /home/dennis/www/coscms/modules/newsletter/admin/validate_all.php

$_COS_LANG_MODULE['newsletter_broken_emails_deleted'] = 'Broken emails deleted';

// Translation of file /home/dennis/www/coscms/modules/newsletter/admin/send.php

$_COS_LANG_MODULE['newsletter_admin_newsletter_note'] = 'Note: It may take some time to send the newsletter, so just press once and wait';
$_COS_LANG_MODULE['newsletter_has_been_sent'] = 'Newsletter has been sent';
$_COS_LANG_MODULE['newsletter_test_has_been_sent'] = 'Newsletter test has been sent';

// Translation of file /home/dennis/www/coscms/modules/newsletter/unsubscribe.php

$_COS_LANG_MODULE['newsletter_unsubscribe_to_newsletter'] = 'Unsubscribe To Newsletter';
$_COS_LANG_MODULE['newsletter_subscribed_message'] = 'You have subscribed to our newsletter';
$_COS_LANG_MODULE['newsletter_unsubscribed_message'] = 'You have unsubscribed to our newsletter. Please check you email and press the confirm link.';

// Translation of file /home/dennis/www/coscms/modules/newsletter/model.newsletter.inc

$_COS_LANG_MODULE['newsletter_subscribe_to_newsletter'] = 'Subscribe To Newsletter';
$_COS_LANG_MODULE['newsletter_subscribe'] = 'Subscribe';
$_COS_LANG_MODULE['newsletter_unsubscribe_to_newsletter'] = 'Unsubscribe To Newsletter';
$_COS_LANG_MODULE['newsletter_unsubscribe'] = 'Unsubscribe';
$_COS_LANG_MODULE['newsletter_email_exists'] = 'Email already exists in database';
$_COS_LANG_MODULE['newsletter_email_not_exists'] = 'Email does not exists';
$_COS_LANG_MODULE['newsletter_error_email'] = 'Error. Email';

$_COS_LANG_MODULE['newsletter_verify_subscribed'] = 'You have subscribed to the newsletter!';
$_COS_LANG_MODULE['newsletter_error_try_later'] = 'Error. Try again later';
$_COS_LANG_MODULE['newsletter_email_already_subscribed'] = 'Email is already subscribed';
$_COS_LANG_MODULE['newsletter_verify_unsubscribed'] = 'You have unsubscribed to our newsletter!';

$_COS_LANG_MODULE['newsletter_subscribe_subject'] = 'Subscribtion';
$_COS_LANG_MODULE['newsletter_unsubscribe_subject'] = 'Unsubscription';
$_COS_LANG_MODULE['newsletter_no_title'] = 'No title';
$_COS_LANG_MODULE['newsletter_no_content'] = 'No content';
$_COS_LANG_MODULE['newsletter_error_test_email'] = 'Error. Test email';

$_COS_LANG_MODULE['newsletter_report_email_error'] = 'Email not correct';
$_COS_LANG_MODULE['newsletter_report_email_correct'] = 'Email correct';
$_COS_LANG_MODULE['newsletter_validate_all_message'] = 'Validate all emails';
$_COS_LANG_MODULE['newsletter_validate_all'] = 'Validate All';
$_COS_LANG_MODULE['newsletter_delete_broken_emails'] = 'Delete broken emails';

// Translation of file /home/dennis/www/coscms/modules/newsletter/subscribe.php

$_COS_LANG_MODULE['newsletter_subscribe_message'] = 'Subscribe to our newsletter';
$_COS_LANG_MODULE['newsletter_subscribe_to_newsletter'] = 'Subscribe to our newsletter';
$_COS_LANG_MODULE['newsletter_subscribed_message'] = 'You have subscribed to our newsletter. Please check you email in a few minutes, and press the confirm link';

$_COS_LANG_MODULE['newsletter_validate_all_emails'] = 'Validate all emails';

$_COS_LANG_MODULE['newsletter_email_already_unsubscribed'] = 'Email is already unsubscribed!';

$_COS_LANG_MODULE['newsletter_archive'] = 'Archive';
$_COS_LANG_MODULE['newsletter_delete_archive_item'] = 'Delete';
$_COS_LANG_MODULE['newsletter_to_top'] = 'Archive Overview';
$_COS_LANG_MODULE['newsletter_archive_html_title_item'] = 'Newsletter Archive';
$_COS_LANG_MODULE['newsletter_archive_html_title'] = 'Newsletter Archive';
$_COS_LANG_MODULE['newsletter_archive_index_meta'] = 'Meta Index';
$_COS_LANG_MODULE['newsletter_add_direct'] = 'newsletter_add_direct';
$_COS_LANG_MODULE['newsletter_form_email'] = 'newsletter_form_email';
$_COS_LANG_MODULE['newsletter_content'] = 'Newsletter Content';
$_COS_LANG_MODULE['newsletter_delete_label'] = 'Delete Newsletter';
$_COS_LANG_MODULE['newsletter_delete_button'] = 'Delete';
$_COS_LANG_MODULE['newsletter_delete_action_message'] = 'Newsletter has been deleted';

$_COS_LANG_MODULE['newsletter_form_event_title'] = 'Recieve newsletter';
