<?php

// Translation of file /home/dennis/www/coscms/modules/newsletter/views/form_send.php

$_COS_LANG_MODULE['send_newsletter'] = 'Send newsletter';
$_COS_LANG_MODULE['title'] = 'Title';
$_COS_LANG_MODULE['content'] = 'Content';
$_COS_LANG_MODULE['test_email'] = 'Test Email';
$_COS_LANG_MODULE['send'] = 'Send';

// Translation of file /home/dennis/www/coscms/modules/newsletter/verify.php

$_COS_LANG_MODULE['newsletter_verify_title'] = 'Verify Subscription';

// Translation of file /home/dennis/www/coscms/modules/newsletter/verify_unsubscribe.php

$_COS_LANG_MODULE['newsletter_verify_unsubscribe_title'] = 'Unsubscribe';

// Translation of file /home/dennis/www/coscms/modules/newsletter/admin/validate_all.php

$_COS_LANG_MODULE['broken_emails_deleted'] = 'Broken emails deleted';

// Translation of file /home/dennis/www/coscms/modules/newsletter/admin/send.php

$_COS_LANG_MODULE['admin_newsletter_note'] = 'Note: It may take some time to send the newsletter, so just press once and wait';
$_COS_LANG_MODULE['newsletter_has_been_sent'] = 'Newsletter has been sent';
$_COS_LANG_MODULE['newsletter_test_has_been_sent'] = 'Newsletter test has been sent';

// Translation of file /home/dennis/www/coscms/modules/newsletter/unsubscribe.php

$_COS_LANG_MODULE['unsubscribe_to_newsletter'] = 'Unsubscribe To Newsletter';
$_COS_LANG_MODULE['subscribed_message'] = 'You have subscribed to our newsletter';
$_COS_LANG_MODULE['unsubscribed_message'] = 'You have unsubscribed to our newsletter. Please check you email and press the confirm link.';

// Translation of file /home/dennis/www/coscms/modules/newsletter/model.newsletter.inc

$_COS_LANG_MODULE['subscribe_to_newsletter'] = 'Subscribe To Newsletter';
$_COS_LANG_MODULE['subscribe'] = 'Subscribe';
$_COS_LANG_MODULE['unsubscribe_to_newsletter'] = 'Unsubscribe To Newsletter';
$_COS_LANG_MODULE['unsubscribe'] = 'Unsubscribe';
$_COS_LANG_MODULE['email_exists'] = 'Email already exists in database';
$_COS_LANG_MODULE['email_not_exists'] = 'Email does not exists';
$_COS_LANG_MODULE['error_email'] = 'Error. Email';

$_COS_LANG_MODULE['verify_subscribed'] = 'You have subscribed to the newsletter!';
$_COS_LANG_MODULE['error_try_later'] = 'Error. Try again later';
$_COS_LANG_MODULE['email_already_subscribed'] = 'Email is already subscribed';
$_COS_LANG_MODULE['verify_unsubscribed'] = 'You have unsubscribed to our newsletter!';

$_COS_LANG_MODULE['subscribe_subject'] = 'Subscribtion';
$_COS_LANG_MODULE['unsubscribe_subject'] = 'Unsubscription';
$_COS_LANG_MODULE['No title'] = 'No title';
$_COS_LANG_MODULE['No content'] = 'No content';
$_COS_LANG_MODULE['error_test_email'] = 'Error. Test email';

$_COS_LANG_MODULE['report_email_error'] = 'Email not correct';
$_COS_LANG_MODULE['report_email_correct'] = 'Email correct';
$_COS_LANG_MODULE['validate_all_message'] = 'Validate all emails';
$_COS_LANG_MODULE['validate_all'] = 'Validate All';
$_COS_LANG_MODULE['delete_broken_emails'] = 'Delete broken emails';

// Translation of file /home/dennis/www/coscms/modules/newsletter/subscribe.php

$_COS_LANG_MODULE['subscribe_message'] = 'Subscribe to our newsletter';
$_COS_LANG_MODULE['subscribe_to_newsletter'] = 'Subscribe to our newsletter';
$_COS_LANG_MODULE['subscribed_message'] = 'You have subscribed to our newsletter. Please check you email in a few minutes, and press the confirm link';

$_COS_LANG_MODULE['validate_all_emails'] = 'Validate all emails';






$_COS_LANG_MODULE['email_already_unsubscribed'] = 'Email is already unsubscribed!';


