<?php

$_MODULE_MENU[] = array (
    'title' => lang::translate('subscribe_to_newsletter'),
    'url' => '/newsletter/subscribe',
);

$_MODULE_MENU[] = array (
    'title' => lang::translate('unsubscribe'),
    'url' => '/newsletter/unsubscribe',
);

$_MODULE_MENU[] = array (
    'title' => lang::translate('newsletter_artchive'),
    'url' => '/newsletter/archive',
);


$_MODULE_MENU[] = array (
    'title' => lang::translate('Admin'),
    'url' => '/newsletter/admin/send',
    'auth' => 'admin'
);




