<?php

$_MODULE_MENU[] = array (
    'title' => lang::translate('newsletter_subscribe_to_newsletter'),
    'url' => '/newsletter/subscribe',
);

$_MODULE_MENU[] = array (
    'title' => lang::translate('newsletter_unsubscribe'),
    'url' => '/newsletter/unsubscribe',
);

$_MODULE_MENU[] = array (
    'title' => lang::translate('newsletter_archive'),
    'url' => '/newsletter/archive',
);


$_MODULE_MENU[] = array (
    'title' => lang::translate('newsletter_admin'),
    'url' => '/newsletter/admin/send',
    'auth' => 'admin'
);




